
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/orders';

const SUPABASE_URL = "https://quzpxwyitxorhdwybddc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1enB4d3lpdHhvcmhkd3liZGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTIyMjEsImV4cCI6MjA2MjI4ODIyMX0.zLFfdL-WQu5bg3nYRd7KXV-SjShkG8T72tj1zQrV9pk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
